#cloud-config

write-files:
  - path: /etc/locustfile.py
    encoding: base64
    content: ${locust_file}

coreos:
  units:
  - name: locust.service
    command: start
    content: |
      [Unit]
      Requires=docker.service
      After=docker.service
      [Service]
      ExecStart=/usr/bin/docker run -p 8089:8089 -p 5557:5557 -p 5558:5558 \
        -v /etc/locustfile.py:/test/locustfile.py \
        hakobera/locust \
        locust -f /test/locustfile.py --master --host=${target_host}
      Restart=always
      RestartSec=10
      [Install]
      WantedBy=multi-user.target
  update:
    reboot-strategy: "off"